package com.restaurant.papricica.exceptions;

public enum ErrorCode {
    INVALID_RESERVATION_TIME,
    TABLE_NOT_FOUND,
    TABLE_NOT_AVAILABLE,
    INVALID_PARTY_SIZE,
    RESERVATION_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    PHONE_NUMBER_ALREADY_EXISTS,
    INVALID_EMAIL_FORMAT,
    INVALID_PHONE_NUMBER_FORMAT,
    RESERVATION_ALREADY_EXISTS
}
