server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/papricica
    username: papricica
    password: papricica

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

security:
  auth:
    header: Authorization
    prefix: "Bearer "
    login-uri: /api/v1/authentication
  jwt:
    secret: ?E(H+MbQeThWmZq4t7w!z%C*F-J@NcRfUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v9
    type: JWT
    issuer: secure-backend
    audience: secure-app
    # 12 hours in milliseconds
    expiration-time: 43200000


management:
  endpoints:
    web:
      exposure:
        include: health,info
