server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/papricica
    username: papricica
    password: papricica

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
